In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/house-prices-advanced-regression-techniques/sample_submission.csv
/kaggle/input/competitions/house-prices-advanced-regression-techniques/data_description.txt
/kaggle/input/competitions/house-prices-advanced-regression-techniques/train.csv
/kaggle/input/competitions/house-prices-advanced-regression-techniques/test.csv

In [4]:
import pandas as pd 
import numpy as np 
import seaborn as sns 
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("/kaggle/input/competitions/house-prices-advanced-regression-techniques/train.csv")

In [6]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [7]:
df.shape

(1460, 81)

In [8]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [10]:
df.corr(numeric_only=True)['SalePrice'].sort_values(ascending=False).head(15)

SalePrice       1.000000
OverallQual     0.790982
GrLivArea       0.708624
GarageCars      0.640409
GarageArea      0.623431
TotalBsmtSF     0.613581
1stFlrSF        0.605852
FullBath        0.560664
TotRmsAbvGrd    0.533723
YearBuilt       0.522897
YearRemodAdd    0.507101
GarageYrBlt     0.486362
MasVnrArea      0.477493
Fireplaces      0.466929
BsmtFinSF1      0.386420
Name: SalePrice, dtype: float64

In [11]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [12]:
df.groupby('YrSold')['SalePrice'].mean()

YrSold
2006    182549.458599
2007    186063.151976
2008    177360.838816
2009    179432.103550
2010    177393.674286
Name: SalePrice, dtype: float64

In [13]:
df.groupby('Neighborhood')['SalePrice'].mean().sort_values(ascending=False)

Neighborhood
NoRidge    335295.317073
NridgHt    316270.623377
StoneBr    310499.000000
Timber     242247.447368
Veenker    238772.727273
Somerst    225379.837209
ClearCr    212565.428571
Crawfor    210624.725490
CollgCr    197965.773333
Blmngtn    194870.882353
Gilbert    192854.506329
NWAmes     189050.068493
SawyerW    186555.796610
Mitchel    156270.122449
NAmes      145847.080000
NPkVill    142694.444444
SWISU      142591.360000
Blueste    137500.000000
Sawyer     136793.135135
OldTown    128225.300885
Edwards    128219.700000
BrkSide    124834.051724
BrDale     104493.750000
IDOTRR     100123.783784
MeadowV     98576.470588
Name: SalePrice, dtype: float64

In [14]:
df.groupby('SaleCondition')['SalePrice'].mean().sort_values(ascending=False)

SaleCondition
Partial    272291.752000
Normal     175202.219533
Alloca     167377.416667
Family     149600.000000
Abnorml    146526.623762
AdjLand    104125.000000
Name: SalePrice, dtype: float64

In [15]:
df.groupby('Foundation')['SalePrice'].mean().sort_values(ascending=False)

Foundation
PConc     225230.442040
Wood      185666.666667
Stone     165959.166667
CBlock    149805.714511
BrkTil    132291.075342
Slab      107365.625000
Name: SalePrice, dtype: float64

In [16]:
X = df.drop('SalePrice',axis=1)
y= df['SalePrice']

In [17]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [18]:
y_test

892     154500
1105    325000
413     115000
522     159000
1036    315500
         ...
479      89471
1361    260000
802     189000
651     108000
722     124500
Name: SalePrice, Length: 292, dtype: int64

In [19]:
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

print("Categorical columns:", len(categorical_cols))
print("Numerical columns:", len(numerical_cols))

Categorical columns: 43
Numerical columns: 37

In [20]:
print(categorical_cols)

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [21]:
print(numerical_cols)

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold'],
      dtype='object')

In [22]:
X_train.isnull().sum().sort_values(ascending=False).head(20)

PoolQC          1162
MiscFeature     1122
Alley           1094
Fence            935
MasVnrType       683
FireplaceQu      547
LotFrontage      217
GarageType        64
GarageQual        64
GarageFinish      64
GarageCond        64
GarageYrBlt       64
BsmtCond          28
BsmtQual          28
BsmtFinType2      28
BsmtFinType1      28
BsmtExposure      28
MasVnrArea         6
Electrical         1
Condition2         0
dtype: int64

In [23]:
X_test.isnull().sum().sort_values(ascending=False).head(20)

PoolQC          291
MiscFeature     284
Alley           275
Fence           244
MasVnrType      189
FireplaceQu     143
LotFrontage      42
GarageType       17
GarageQual       17
GarageFinish     17
GarageCond       17
GarageYrBlt      17
BsmtExposure     10
BsmtFinType2     10
BsmtFinType1      9
BsmtQual          9
BsmtCond          9
MasVnrArea        2
BldgType          0
Condition2        0
dtype: int64

In [24]:
none_cols = [
    'PoolQC', 'MiscFeature', 'Alley', 'Fence',
    'MasVnrType', 'FireplaceQu',
    'GarageType', 'GarageQual', 'GarageFinish', 'GarageCond',
    'BsmtQual', 'BsmtCond', 'BsmtExposure',
    'BsmtFinType1', 'BsmtFinType2'
]

In [25]:
X_train[none_cols] = X_train[none_cols].fillna('None')
X_test[none_cols] = X_test[none_cols].fillna('None')

In [26]:
X_train.isnull().sum().sort_values(ascending=False).head(20)

LotFrontage     217
GarageYrBlt      64
MasVnrArea        6
Electrical        1
LotArea           0
Id                0
MSSubClass        0
MSZoning          0
LandContour       0
Utilities         0
LotConfig         0
LandSlope         0
Neighborhood      0
Street            0
Alley             0
LotShape          0
BldgType          0
Condition2        0
Condition1        0
OverallCond       0
dtype: int64

In [27]:
X_test.isnull().sum().sort_values(ascending=False).head(20)

LotFrontage     42
GarageYrBlt     17
MasVnrArea       2
Id               0
LotArea          0
Street           0
MSSubClass       0
MSZoning         0
LandContour      0
Utilities        0
LotConfig        0
LandSlope        0
Neighborhood     0
Condition1       0
Alley            0
LotShape         0
BldgType         0
Condition2       0
OverallCond      0
HouseStyle       0
dtype: int64

In [28]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [29]:
numerical_transformer = SimpleImputer(strategy='median')

In [30]:
from sklearn.pipeline import Pipeline

In [31]:
categorical_transformer = Pipeline([
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore'))
])

In [32]:
preprocessor = ColumnTransformer([
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

In [33]:
X_train_processed = preprocessor.fit_transform(X_train)

X_test_processed = preprocessor.transform(X_test)

In [34]:
 X_train_processed.shape

(1168, 301)

In [35]:
X_test_processed.shape

(292, 301)

In [36]:
# linear regression 
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train_processed , y_train)

LinearRegression()

In [37]:
y_pred = model.predict(X_test_processed)

In [38]:
y_pred[:5]

array([158745.40011508, 351013.046806  , 101175.90250027, 179400.23225085,
       342380.4874479 ])

In [39]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [40]:
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mean_squared_error(y_test,y_pred))
r2 = r2_score(y_test,y_pred)
print("MAE:",mae)
print("RMSE",rmse)
print("R2 score",r2)

MAE: 20433.88623077463
RMSE 31085.094649427647
R2 score 0.8740232053679198

In [41]:
from sklearn.metrics import mean_absolute_percentage_error

mape = mean_absolute_percentage_error(y_test, y_pred)

print("MAPE:", mape)
print("MAPE %:", mape * 100)
# (MAPE) batata hai ki model ki prediction actual value se average kitne percent different hai.

MAPE: 0.12622323404508667
MAPE %: 12.622323404508668

In [42]:
import numpy as np

y_train_log = np.log1p(y_train)

In [43]:
# Linear Regression ko log target par train karo
model_log = LinearRegression()

model_log.fit(X_train_processed, y_train_log)

LinearRegression()

In [44]:
y_pred_log = model_log.predict(X_test_processed)

In [45]:
y_pred_log_original = np.expm1(y_pred_log)
# prediction log scale par hai. Hume actual rupees mein wapas lana hai:

In [46]:
mae_log = mean_absolute_error(y_test, y_pred_log_original)
rmse_log = np.sqrt(mean_squared_error(y_test, y_pred_log_original))
r2_log = r2_score(y_test, y_pred_log_original)
mape_log = mean_absolute_percentage_error(y_test, y_pred_log_original)

print("MAE:", mae_log)
print("RMSE:", rmse_log)
print("R²:", r2_log)
print("MAPE:", mape_log * 100, "%")

MAE: 16965.715160189855
RMSE: 25487.14016956009
R²: 0.9153107317112366
MAPE: 10.302293205156255 %

In [47]:
from sklearn.linear_model import Ridge 
ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train_processed,y_train_log)

Ridge()

In [48]:
ridge_pred_log = ridge_model.predict(X_test_processed)
ridge_pred = np.expm1(ridge_pred_log)

In [49]:
ridge_mae = mean_absolute_error(y_test, ridge_pred)
ridge_rmse = np.sqrt(mean_squared_error(y_test, ridge_pred))
ridge_r2 = r2_score(y_test, ridge_pred)
ridge_mape = mean_absolute_percentage_error(y_test, ridge_pred)

print("MAE:", ridge_mae)
print("RMSE:", ridge_rmse)
print("R²:", ridge_r2)
print("MAPE:", ridge_mape * 100, "%")

MAE: 17924.433459235082
RMSE: 29462.080145604956
R²: 0.8868347782011257
MAPE: 10.604709912368453 %

In [50]:
# RANDOM FOREST 
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

In [51]:
rf_model.fit(X_train_processed,y_train)

RandomForestRegressor(n_estimators=300, n_jobs=-1, random_state=42)

In [52]:
rf_pred = rf_model.predict(X_test_processed)

In [53]:
rf_mae = mean_absolute_error(y_test, rf_pred)
rf_rmse = np.sqrt(mean_squared_error(y_test, rf_pred))
rf_r2 = r2_score(y_test, rf_pred)
rf_mape = mean_absolute_percentage_error(y_test, rf_pred)

print("MAE:", rf_mae)
print("RMSE:", rf_rmse)
print("R²:", rf_r2)
print("MAPE:", rf_mape * 100, "%")

MAE: 17465.43152968036
RMSE: 29003.59980858004
R²: 0.8903294619897589
MAPE: 10.671046165499694 %

In [54]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

In [55]:
rf= RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

In [56]:
param_grid={
    'n_estimators':[100,200,300,500],
    'max_depth':[None,10,20,30],
    'min_samples_split':[2,5,10],
    'min_samples_leaf':[1,2,4],
    'max_features':['sqrt','log2',0.8]
}

In [57]:
rf_random = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    scoring='neg_mean_absolute_error',
    random_state=42,
    n_jobs=-1
)

In [58]:
rf_random.fit(X_train_processed, y_train)

RandomizedSearchCV(cv=5,
                   estimator=RandomForestRegressor(n_jobs=-1, random_state=42),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'max_depth': [None, 10, 20, 30],
                                        'max_features': ['sqrt', 'log2', 0.8],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 200, 300, 500]},
                   random_state=42, scoring='neg_mean_absolute_error')

In [59]:
rf_random.best_params_

{'n_estimators': 500,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 0.8,
 'max_depth': None}

In [60]:
# prediction 
best_rf = rf_random.best_estimator_

rf_tuned_pred = best_rf.predict(X_test_processed)

In [61]:
rf_tuned_mae = mean_absolute_error(y_test, rf_tuned_pred)
rf_tuned_rmse = np.sqrt(mean_squared_error(y_test, rf_tuned_pred))
rf_tuned_r2 = r2_score(y_test, rf_tuned_pred)
rf_tuned_mape = mean_absolute_percentage_error(y_test, rf_tuned_pred)

print("MAE:", rf_tuned_mae)
print("RMSE:", rf_tuned_rmse)
print("R²:", rf_tuned_r2)
print("MAPE:", rf_tuned_mape * 100, "%")

MAE: 17145.624390410958
RMSE: 28570.063285055505
R²: 0.8935835981333821
MAPE: 10.513441740422516 %

In [62]:
# XG Boosting
import xgboost as xgb

In [63]:
from xgboost import XGBRegressor

xgb_model = XGBRegressor(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=3,
    random_state=42,
    n_jobs=-1
)

In [64]:
xgb_model.fit(X_train_processed, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=-1, num_parallel_tree=None, ...)

In [65]:
xgb_pred = xgb_model.predict(X_test_processed)

In [66]:
xgb_mae = mean_absolute_error(y_test, xgb_pred)
xgb_rmse = np.sqrt(mean_squared_error(y_test, xgb_pred))
xgb_r2 = r2_score(y_test, xgb_pred)
xgb_mape = mean_absolute_percentage_error(y_test, xgb_pred)

print("MAE:", xgb_mae)
print("RMSE:", xgb_rmse)
print("R²:", xgb_r2)
print("MAPE:", xgb_mape * 100, "%")

MAE: 16722.91015625
RMSE: 26520.457311290844
R²: 0.9083044528961182
MAPE: 9.934205561876297 %

In [67]:
xgb_param_grid = {
    'n_estimators': [200, 300, 500, 700],
    'learning_rate': [0.01, 0.03, 0.05, 0.1],
    'max_depth': [2, 3, 4, 5, 6],
    'min_child_weight': [1, 3, 5],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'gamma': [0, 0.1, 0.2]
}

In [68]:
xgb_model = XGBRegressor(
    random_state=42,
    n_jobs=-1
)

In [69]:
# RandomizedSearchCV
xgb_random = RandomizedSearchCV(
    estimator=xgb_model,
    param_distributions=xgb_param_grid,
    n_iter=20,
    cv=5,
    scoring='neg_mean_absolute_error',
    random_state=42,
    n_jobs=-1
)

In [70]:
xgb_random.fit(X_train_processed, y_train)

RandomizedSearchCV(cv=5,
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          callbacks=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, device=None,
                                          early_stopping_rounds=None,
                                          enable_categorical=True,
                                          eval_metric=None, feature_types=None,
                                          feature_weights=None, gamma=None,
                                          grow_policy=None,
                                          importance_type=None,
                                          interaction_constraints...
                                          multi_strategy=None,
                                          n_estimators=None, n_jobs=-1,
                                          num_parallel_tree=None, ...),
                   n_iter=20, n_jobs=-1,
                   param_distributions={'colsample_bytree': [0.7, 0.8, 1.0],
                                        'gamma': [0, 0.1, 0.2],
                                        'learning_rate': [0.01, 0.03, 0.05,
                                                          0.1],
                                        'max_depth': [2, 3, 4, 5, 6],
                                        'min_child_weight': [1, 3, 5],
                                        'n_estimators': [200, 300, 500, 700],
                                        'subsample': [0.7, 0.8, 1.0]},
                   random_state=42, scoring='neg_mean_absolute_error')

In [71]:
xgb_random.best_params_

{'subsample': 0.8,
 'n_estimators': 700,
 'min_child_weight': 5,
 'max_depth': 4,
 'learning_rate': 0.05,
 'gamma': 0,
 'colsample_bytree': 0.7}

In [72]:
best_xgb = xgb_random.best_estimator_

xgb_tuned_pred = best_xgb.predict(X_test_processed)

In [73]:
xgb_tuned_mae = mean_absolute_error(y_test, xgb_tuned_pred)
xgb_tuned_rmse = np.sqrt(mean_squared_error(y_test, xgb_tuned_pred))
xgb_tuned_r2 = r2_score(y_test, xgb_tuned_pred)
xgb_tuned_mape = mean_absolute_percentage_error(y_test, xgb_tuned_pred)

print("MAE:", xgb_tuned_mae)
print("RMSE:", xgb_tuned_rmse)
print("R²:", xgb_tuned_r2)
print("MAPE:", xgb_tuned_mape * 100, "%")

MAE: 15265.4248046875
RMSE: 24451.514145344863
R²: 0.922053337097168
MAPE: 9.302348643541336 %

In [74]:
# feature enginerring
# total area combine 
X_train['TotalSF'] = X_train['TotalBsmtSF'] + X_train['1stFlrSF'] + X_train['2ndFlrSF']

X_test['TotalSF'] = X_test['TotalBsmtSF'] + X_test['1stFlrSF'] + X_test['2ndFlrSF']

In [75]:
X_train[['TotalBsmtSF', '1stFlrSF', '2ndFlrSF', 'TotalSF']].head()

      TotalBsmtSF  1stFlrSF  2ndFlrSF  TotalSF
254          1314      1314         0     2628
1066          799       799       772     2370
638           796       796         0     1592
799           731       981       787     2499
380          1026      1026       665     2717

In [76]:
# TotalSF ko numerical columns me add kro
numerical_cols = list(numerical_cols) + ['TotalSF']

In [77]:
# Preprocessor dobara banao
numerical_transformer = SimpleImputer(strategy='median')

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

In [78]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [79]:
X_train_processed.shape

(1168, 302)

In [80]:
# input change now again XG boost train 
best_xgb_fe = XGBRegressor(
    n_estimators=700,
    learning_rate=0.05,
    max_depth=4,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.7,
    gamma=0,
    random_state=42,
    n_jobs=-1
)

best_xgb_fe.fit(X_train_processed, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.7, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=5, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=700,
             n_jobs=-1, num_parallel_tree=None, ...)

In [81]:
xgb_fe_pred = best_xgb_fe.predict(X_test_processed)

In [82]:
print("MAE:", mean_absolute_error(y_test, xgb_fe_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, xgb_fe_pred)))
print("R²:", r2_score(y_test, xgb_fe_pred))
print("MAPE:", mean_absolute_percentage_error(y_test, xgb_fe_pred) * 100, "%")

MAE: 15836.947265625
RMSE: 24965.85828686849
R²: 0.9187395572662354
MAPE: 9.64355319738388 %

In [83]:
# bathroom
X_train['TotalBathrooms'] = (
    X_train['FullBath']
    + 0.5 * X_train['HalfBath']
    + X_train['BsmtFullBath']
    + 0.5 * X_train['BsmtHalfBath']
)

X_test['TotalBathrooms'] = (
    X_test['FullBath']
    + 0.5 * X_test['HalfBath']
    + X_test['BsmtFullBath']
    + 0.5 * X_test['BsmtHalfBath']
)

In [84]:
X_train[['FullBath', 'HalfBath', 'BsmtFullBath', 'BsmtHalfBath', 'TotalBathrooms']].head()

      FullBath  HalfBath  BsmtFullBath  BsmtHalfBath  TotalBathrooms
254          1         0             1             0             2.0
1066         2         1             0             0             2.5
638          1         0             0             0             1.0
799          1         1             1             0             2.5
380          2         0             0             0             2.0

In [85]:
numerical_cols = list(numerical_cols) + ['TotalBathrooms']

In [86]:
numerical_transformer = SimpleImputer(strategy='median')

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

In [87]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [88]:
X_train_processed.shape

(1168, 303)

In [89]:
best_xgb_bath = XGBRegressor(
    n_estimators=700,
    learning_rate=0.05,
    max_depth=4,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.7,
    gamma=0,
    random_state=42,
    n_jobs=-1
)

best_xgb_bath.fit(X_train_processed, y_train)

xgb_bath_pred = best_xgb_bath.predict(X_test_processed)

In [90]:
print("MAE:", mean_absolute_error(y_test, xgb_bath_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, xgb_bath_pred)))
print("R²:", r2_score(y_test, xgb_bath_pred))
print("MAPE:", mean_absolute_percentage_error(y_test, xgb_bath_pred) * 100, "%")

MAE: 15544.8662109375
RMSE: 24752.24951393307
R²: 0.9201241731643677
MAPE: 9.432841092348099 %

In [91]:
X_train['HouseAge'] = X_train['YrSold'] - X_train['YearBuilt']

X_test['HouseAge'] = X_test['YrSold'] - X_test['YearBuilt']

In [92]:
X_train[['YearBuilt', 'YrSold', 'HouseAge']].head()

      YearBuilt  YrSold  HouseAge
254        1957    2010        53
1066       1993    2009        16
638        1910    2008        98
799        1937    2007        70
380        1924    2010        86

In [93]:
numerical_cols = list(numerical_cols) + ['HouseAge']

In [94]:
numerical_transformer = SimpleImputer(strategy='median')

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

In [95]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [96]:
best_xgb_age = XGBRegressor(
    n_estimators=700,
    learning_rate=0.05,
    max_depth=4,
    min_child_weight=5,
    subsample=0.8,
    colsample_bytree=0.7,
    gamma=0,
    random_state=42,
    n_jobs=-1
)

best_xgb_age.fit(X_train_processed, y_train)

xgb_age_pred = best_xgb_age.predict(X_test_processed)

In [97]:
print("MAE:", mean_absolute_error(y_test, xgb_age_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, xgb_age_pred)))
print("R²:", r2_score(y_test, xgb_age_pred))
print("MAPE:", mean_absolute_percentage_error(y_test, xgb_age_pred) * 100, "%")

MAE: 15396.236328125
RMSE: 24819.280247420553
R²: 0.9196909666061401
MAPE: 9.396230429410934 %

In [98]:
X_train = X_train.drop(columns=['TotalSF', 'TotalBathrooms', 'HouseAge'])
X_test = X_test.drop(columns=['TotalSF', 'TotalBathrooms', 'HouseAge'])

In [99]:
# numerical col og list reset
numerical_cols = X.select_dtypes(exclude='object').columns

In [102]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

ValueError: A given column is not a column of the dataframe

In [103]:
numerical_cols = X.select_dtypes(exclude='object').columns.tolist()

In [104]:
numerical_transformer = SimpleImputer(strategy='median')

categorical_transformer = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numerical_transformer, numerical_cols),
    ('cat', categorical_transformer, categorical_cols)
])

In [105]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [106]:
X_train_processed.shape

(1168, 301)

In [107]:
best_xgb = xgb_random.best_estimator_

In [108]:
best_xgb.fit(X_train_processed, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.7, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=0, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
             max_leaves=None, min_child_weight=5, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=700,
             n_jobs=-1, num_parallel_tree=None, ...)

In [109]:
xgb_final_pred = best_xgb.predict(X_test_processed)

In [110]:
print("MAE:", mean_absolute_error(y_test, xgb_final_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, xgb_final_pred)))
print("R²:", r2_score(y_test, xgb_final_pred))
print("MAPE:", mean_absolute_percentage_error(y_test, xgb_final_pred) * 100, "%")

MAE: 15265.4248046875
RMSE: 24451.514145344863
R²: 0.922053337097168
MAPE: 9.302348643541336 %

In [111]:
best_xgb.fit(X_train_processed, y_train)

xgb_final_pred = best_xgb.predict(X_test_processed)

print("R²:", r2_score(y_test, xgb_final_pred))

R²: 0.922053337097168

In [112]:
# predicting on datasets

In [113]:
test = pd.read_csv(
    '/kaggle/input/competitions/house-prices-advanced-regression-techniques/test.csv'
)

In [114]:
test.shape

(1459, 80)

In [115]:
test[none_cols] = test[none_cols].fillna('None')

In [116]:
X_kaggle_test_processed = preprocessor.transform(test)

In [117]:
X_kaggle_test_processed.shape

(1459, 301)

In [118]:
final_predictions = best_xgb.predict(X_kaggle_test_processed)

In [119]:
final_predictions[:5]

array([128680.86, 164086.19, 188996.23, 204017.8 , 195074.83],
      dtype=float32)

In [120]:
test_ids = test['Id']

In [121]:
submission = pd.DataFrame({
    'Id': test_ids,
    'SalePrice': final_predictions
})

In [122]:
submission.head()

     Id      SalePrice
0  1461  128680.859375
1  1462  164086.187500
2  1463  188996.234375
3  1464  204017.796875
4  1465  195074.828125

In [125]:
# save in csv file
submission.to_csv('submission.csv', index=False)

In [126]:
submission.shape

(1459, 2)